### ISSUE TITLE
Syntax error: Operator expected

### ISSUE THREAD

**Issue by georgewangchn** [ciao-lang/mycin#1]
Syntax error: Operator expected:【bagof(CFArg, MycinGoal(CFArg), OR_CF_List)】

cf(MycinGoal,ResultingCF) :-
    if(
	bagof(CFArg, MycinGoal(CFArg), OR_CF_List),
	or_CF_inference(OR_CF_List,ResultingCF),
	ResultingCF = 0
	).

**Comment by mherme** [comment]
What version of the system are you using? That file loads without error in the current installed version or in the playground: http://ciao-lang.org/playground/ 
Btw, to find help for a given predicate or symbol in general (e.g., term/1 or if/3) you can type C-h S (Help for current Symbol) in Emacs, or in the manuals search: http://ciao-lang.org/ciao/build/doc/ciao.html/ciaosearch.html

**Comment by jfmc** [comment]
We'd need a bit of context to understand the issue (note that the parentheses in your report contains unicode symbols, is that intended?)
